version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./pgdata:/postgresql/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    -  /usr/src/app/node_modules