const swaggerAutogen = require("swagger-autogen");
const dotenv = require("dotenv");
dotenv.config();
// eslint-disable-line global-require
swaggerAutogen();

const doc = {
  info: {
    version: "1.0.0",
    title: "Pharmacy API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be 'header', 'query' or 'cookie'
      name: "Authorization", // name of the header, query parameter or cookie
      description: "Some description...",
    },
  },
  host:
    process.env.NODE_ENV === "production" ? "medicine-crm.herokuapp.com" : "localhost:3000",
  basePath: "/",
  schemes: ["http","https"],
  consumes: ["application/json"],
  produces: ["application/json"],
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./src/index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  // eslint-disable-next-line global-require
  require("./src/index"); // Your project's root file
});
